mia-platform/miactl

.gitignore, Makefile
Add a Makefile ispired by [this](https://github.com/derailed/k9s/blob/master/Makefile).
Adds several features:
- Test
- Coverage
- Build, passing variables to give the ability to create `version` command reliable
- Docker image build ( for when will be available a dockerfile )
- Help
=> add makefile

.gitignore, README.md, cmd/completion.go, cmd/completion_test.go, cmd/get.go, cmd/get_test.go, cmd/root.go
=> Add completion for fish, bash and zsh

internal/cmd/login/login.go
This PR updates the GetTokensWithOIDC function to shutdown the server gracefully and close the browser tab automatically.
=> Feat: update login to close browser window

internal/cmd/company/company.go, internal/cmd/company/company_test.go, internal/cmd/company/list.go, internal/cmd/company/list_test.go, internal/cmd/resources/resources.go, internal/cmd/root.go, internal/httphandler/httphandler.go, internal/testutils/testutils.go
This PR adds the command and helper functions to list the companies of the current context.
=> Feat: company list command

internal/cmd/context/context.go, internal/cmd/context/context_test.go, internal/cmd/context/list.go, internal/cmd/context/list_test.go, internal/cmd/context/use.go
This PR adds support to show the list of contexts, marking the current one with a star (*).
=> Feat: add context list command

internal/cmd/company.go, internal/cmd/marketplace.go, internal/cmd/marketplace/list.go, internal/cmd/marketplace/list_test.go, internal/resources/responses.go
[SMTM-8](https://makeitapp.atlassian.net/browse/SMTM-8)
=> feat(SMTM-8): list marketplace items

.github/workflows/dependency-review.yaml, .goreleaser.yaml, CHANGELOG.md, docs/30_commands.md, internal/cmd/context.go, internal/cmd/environments/doc.go, internal/cmd/environments/environments.go, internal/cmd/environments/environments_test.go, internal/cmd/project/list.go, internal/cmd/root.go, internal/cmd/runtime.go, internal/resources/responses.go, tools/make/container.mk
This PR introduce a new first level command `runtime` and its first subcommand `environment list` that will show the user all runtime environment associated to a given project.
=> New Command for listing environments

internal/cmd/marketplace/apply/apply.go, internal/cmd/marketplace/apply/apply_test.go, internal/cmd/marketplace/apply/table.go, internal/cmd/marketplace/apply/testdata/subdir/validItem1.json, internal/cmd/marketplace/apply/testdata/subdir/validItemWithImage.json, internal/cmd/marketplace/apply/testdata/subdir/validYaml.yaml, internal/cmd/marketplace/apply/testdata/subdir/validYaml.yml, internal/cmd/marketplace/apply/testdata/validItem1.json, internal/cmd/marketplace/apply/testdata/validItemWithImage.json, internal/cmd/marketplace/apply/testdata/validItemWithImage2.json, internal/cmd/marketplace/apply/testdata/validYaml.yaml, internal/cmd/marketplace/apply/testdata/validYaml.yml, internal/cmd/marketplace/apply/testdata/yamlWithImage.yml, internal/resources/marketplace/marketplace.go
Moves uniqueness field check from `name` to `itemId`.
=> Uniqueness check based on itemId

docs/20_setup.md, docs/30_commands.md
Document on how to install on Windows WSL
=> docs: install on Windows with WSL

docs/20_setup.md
Update the documentation to provide the proper command for installing `miactl` via `go install` method
=> fix(docs): command to install miactl via go install

internal/cmd/marketplace/apply/apply.go, internal/cmd/marketplace/apply/apply_test.go, internal/cmd/marketplace/delete.go, internal/cmd/marketplace/get.go, internal/cmd/marketplace/list.go, internal/cmd/marketplace/list_test.go, internal/resources/responses.go
Add ITEM ID to the table returned by the command `miactl marketplace list`
**Which issue(s) this PR fixes:**
- Do not show help of the command when errors are not due to bad command arg syntax
=> feat: better err handling, show item id in marketplace list

CHANGELOG.md, docs/30_commands.md, internal/cmd/marketplace.go, internal/cmd/marketplace/apply/apply.go, internal/cmd/marketplace/delete.go, internal/cmd/marketplace/get.go, internal/cmd/marketplace/list.go
Removes beta annotations related to miactl marketplace commands
=> chore: remove marketplace beta annotations

docs/10_overview.md
Adds `marketplace` command reference to `miactl` overview documentation
=> chore: documentation

CHANGELOG.md, docs/30_commands.md, internal/clioptions/clioptions.go, internal/cmd/marketplace/apply/apply.go, internal/cmd/marketplace/delete.go, internal/cmd/marketplace/get.go, internal/cmd/marketplace/get_test.go, internal/cmd/marketplace/list.go, internal/cmd/marketplace/list_versions.go, internal/cmd/marketplace/list_versions_test.go, internal/resources/marketplace/marketplace.go
Add support to get marketplace item by itemID+version tuple
=> feat: Add support to get marketplace item by itemID+version tuple

CHANGELOG.md, docs/30_commands.md, internal/cmd/marketplace.go, internal/cmd/marketplace/delete.go, internal/cmd/marketplace/get.go
Exclude marketplace alpha features when compilation flag ALPHA is not set
=> feat: mark marketplace alpha features

CHANGELOG.md, docs/30_commands.md, internal/client/response.go, internal/clioptions/clioptions.go, internal/cmd/company/iam/group/remove.go, internal/cmd/company/iam/group/remove_member.go, internal/cmd/company/iam/group/remove_member_test.go, internal/cmd/company/iam/group/remove_test.go, internal/cmd/company/iam/remove.go, internal/cmd/company/iam/serviceaccount/jwt/jwt.go, internal/cmd/company/iam/serviceaccount/remove.go, internal/cmd/company/iam/serviceaccount/remove_test.go, internal/cmd/company/iam/user/remove.go, internal/cmd/company/iam/user/remove_test.go, internal/resources/requests.go
This PR will add the last commands for the iam subcommand for companies. It will add the ability to remove users, groups, service account from a company and also remove member from groups.
=> Add remove family of iam commands

internal/cmd/marketplace/list.go
This PR removes a duplicated `FLAGS` into `miactl marketplace list --help` command
=> fix: update marketplace list help command

internal/cmd/extensions/client.go, internal/cmd/extensions/client_test.go, internal/cmd/extensions/cmd.go, internal/cmd/extensions/delete.go
Introduce delete extension api as defined in #198 
**Which issue(s) this PR fixes:**
- Fixes #198
=> feat: delete extension api

docs/30_commands.md, docs/40_examples.md
Improve documentation.
* Add '--auth-name' flag in the 'Context set' paragraph;
* Add example of deploy in a CD pipeline.
=> Improve authentication documentation

docs/30_commands.md
Minor docs improvements to extensions command
=> docs: improved docs

CHANGELOG.md, docs/30_commands.md, internal/cmd/extensions/client.go, internal/cmd/extensions/client_test.go, internal/cmd/extensions/cmd.go, internal/cmd/extensions/getone.go, internal/cmd/extensions/getone_test.go, internal/cmd/extensions/list.go, internal/resources/extensibility/extensionInfo.go, internal/resources/extensibility/extensions.go
This PR introduces the command to use a new Console API to get a specific extension
=> feat: get extension by id

internal/cmd/extensions/client.go, internal/cmd/extensions/client_test.go, internal/cmd/extensions/list.go, internal/cmd/extensions/list_test.go, internal/resources/extensibility/extensionInfo.go
This PR introduces the retrieval of the new fields returned by the extension list api, it also fixes an issue with the extension by id api `name` field
=> feat: extend extension list result and fixed new model name field

internal/clioptions/clioptions.go, internal/cmd/extensions/activate.go, internal/cmd/extensions/apply.go, internal/cmd/extensions/client.go, internal/cmd/extensions/client_test.go, internal/cmd/extensions/cmd.go, internal/cmd/extensions/deactivate.go, internal/cmd/extensions/delete.go, internal/cmd/extensions/getone.go, internal/cmd/extensions/list.go, internal/cmd/extensions/list_test.go, internal/resources/extensibility/extensionInfo.go
Fixed and extended the get extensions by list command to accept the resolve-details flag and support the optional resolution of extension menu and category
=> feat: resolve-detail flag for get extensions list

docs/40_examples.md
It's a little documentation improve to try to solve this issue https://github.com/mia-platform/miactl/issues/156
=> Changed docs example for PaaS Commands

docs/30_commands.md
Just fixed a typo in documentation
=> docs: typo in documentation

docs/30_commands.md
This PR adds the documentation for `project describe` and `project apply` commands
=> Added documentation for `project describe` and `project apply` commands
