- .github/workflows/release.yml
- goreleaser.yml
This implements #4 
I'm using my account to do the commit in the homebrew-tap repo. If this works we should consider create a bot account.
After merge make a tag and magic should happen
> add ci releases and brew tap

- CHANGELOG.md
- sdk/deploy.go
- sdk/deploy_test.go
Deployment API will soon be migrated from `/api/backend` to `/api/deploy`, this PR will come handy when the migration goes in production
> Deploy api migration

- cmd/console/deploy/deploy.go
- cmd/console/deploy/status.go
- cmd/console/deploy/status_test.go
- sdk/client.go
- sdk/deploy.go
- sdk/deploy_test.go
- sdk/testing.go
**Note:** This Pull Request should be reviewed only after #40 is closed, since it builds on top of it.
Add a new command that acts on the console resource. This command should check the deploy status of all the pipelines that have been previously triggered using the `deploy` command of `miactl`.
Note: this command does not allow to select a pipeline of a specific project.
```shell
miactl console deploy status
```
> Feature: new deploy status command to monitor the status

- internal/cmd/root.go
- internal/httphandler/auth.go
- internal/httphandler/credentials.go
- internal/httphandler/credentials_test.go
This PR adds support for saving login tokens in files, to avoid logging in at each API request.
The JSON tokens are saved in separate files, named with the SHA256 of the endpoint.
> Feat: save login tokens in files

- CHANGELOG.md
- docs/30_commands.md
- internal/cmd/deployments/deployments.go
- internal/cmd/deployments/deployments_test.go
- internal/cmd/deployments/doc.go
- internal/cmd/runtime.go
- internal/resources/responses.go
This PR will add a new runtime subcommand `runtime deployment list`. This command will print all the deployments associated with a project and environment. The information shown are comparable to the ones that a possible `kubectl` command will show.
> Add runtime deployment list subcommand

- CHANGELOG.md
- docs/30_commands.md
- internal/cmd/events/deployments_test.go
- internal/cmd/events/doc.go
- internal/cmd/events/events.go
- internal/cmd/runtime.go
- internal/resources/responses.go
New events subcommand for `runtime`, it can show related events to resources in a specific environment of a project. The output is similar to the one of `kubectl get envents`.
> Add runtime events command

- CHANGELOG.md
- internal/cmd/marketplace/apply/apply_test.go
- internal/cmd/marketplace/apply/table.go
- internal/resources/marketplace/marketplace.go
Change the output of the `miactl marketplace apply`  command in order to show the `itemId` instead of the `name`
> feat(SMTM-38): show item id in marketplace apply responses, remove name

- CHANGELOG.md
- internal/cmd/version.go
Fix the help text of the `version` command, replacing `mlp` with `miactl`
> fix: version help text

- CHANGELOG.md
- internal/cmd/marketplace/apply/apply.go
- internal/cmd/marketplace/apply/apply_test.go
marketplace apply: silently ignore files with invalid extension rather than throwing error
> fix: marketplace apply should silently ignore unsupported files

- CHANGELOG.md
- docs/30_commands.md
- internal/clioptions/clioptions.go
- internal/cmd/marketplace/delete.go
- internal/cmd/marketplace/delete_test.go
- internal/cmd/marketplace/list_versions.go
- internal/cmd/marketplace/list_versions_test.go
- internal/resources/marketplace/marketplace.go
Modified `miactl marketplace delete` command to accept either the `objectId` or a `itemId`-`version` tuple that identifies the item to be deleted.
> feat: marketplace delete item by itemId+version tuple

- docs/30_commands.md
- internal/cmd/logs/logs.go
- internal/cmd/resources/list.go
- internal/cmd/runtime.go
This PR will both improve the public docs and helper of `runtime logs` and `runtime list` commands and add a brand new command `runtime api-resources` for listing available resource types that can be used with the list command.
This will improve the DX of those commands as highlighted by this community discussion https://github.com/mia-platform/community/discussions/343
> feat: improve runtime command usage

- CHANGELOG.md
- docs/30_commands.md
- internal/client/client.go
- internal/clioptions/clioptions.go
- internal/cmd/company/iam/edit.go
- internal/cmd/company/iam/group/create.go
- internal/cmd/company/iam/group/create_test.go
- internal/cmd/company/iam/group/edit.go
- internal/cmd/company/iam/group/edit_test.go
- internal/cmd/company/iam/serviceaccount/basic/basic.go
- internal/cmd/company/iam/serviceaccount/basic/basic_test.go
- internal/cmd/company/iam/serviceaccount/edit.go
- internal/cmd/company/iam/serviceaccount/edit_test.go
- internal/cmd/company/iam/serviceaccount/jwt/jwt.go
- internal/cmd/company/iam/serviceaccount/jwt/jwt_test.go
- internal/cmd/company/iam/user/create.go
- internal/cmd/company/iam/user/create_test.go
- internal/cmd/company/iam/user/edit.go
- internal/cmd/company/iam/user/edit_test.go
- internal/resources/requests.go
- internal/resources/utils.go
- internal/resources/utils_test.go
This PR will add all the various edit commands for the IAM resources of a company and tidy up the completion code for the roles shared between multiple commands to be easier to change and maintain in the future.
> Add `edit` family of iam commands

- CHANGELOG.md
- internal/cmd/root.go
The documentation link shown in the root cmd pointed to example.org, fixed to mia-platform.eu
> fix: documentation link in root command

- CHANGELOG.md
- internal/clioptions/clioptions.go
Remove the conflicting shorthand flag `-v` for flag `--version` of the command `miactl marketplace delete`
> fix: remove conflicting flag from marketplace delete command

- CHANGELOG.md
- docs/30_commands.md
- internal/clioptions/clioptions.go
- internal/cmd/marketplace/list.go
- internal/cmd/marketplace/list_test.go
- internal/resources/marketplace/marketplace.go
- internal/resources/responses.go
This PR adds the `--public` flag  to `marketplace list` command in order to allow users to retrieve public marketplace items.
> feat: add public flag to marketplace list

- docs/30_commands.md
- internal/cmd/marketplace/list.go
Fix `miactl marketplace list` to use context `company-id` when not specified as cli option
> fix: marketplace list with context companyID

- CHANGELOG.md
- internal/authorization/browser_linux.go
I find some problems using the miactl on Linux and the problem is related to command `open` instead of `xdg-open`.
I tested on my machine but I didn't find any specific tests for this case.
> Fix open browser on Linux

- CHANGELOG.md
- internal/cmd/marketplace/apply/apply_test.go
- internal/cmd/marketplace/apply/table.go
Fix the output of the `miactl marketplace apply` command to display `OBJECT ID` rather than `ID`  for consistency with other commands.
> fix: `marketplace apply` cmd output

- docs/20_setup.md
Updated link to github from `ghr.io` to `gchr.io`
> Fix github url ghr to gchr and updated docker syntax

- docs/30_commands.md
Added the context name to the `miactl auth` command, without context `miactl auth` does not work
> Added context to auth

- CHANGELOG.md
- internal/cmd/deploy/deploy.go
- internal/cmd/deploy/deploy_test.go
**Which issue(s) this PR fixes:**
Fixes a bug get deploy status in provider which differs from gitlab.
> fix: sends environment query params when get the deploy status

- CHANGELOG.md
- docs/30_commands.md
- internal/clioptions/clioptions.go
- internal/cmd/deploy/deploy.go
- internal/cmd/deploy/status.go
- internal/cmd/deploy/status_test.go
- internal/cmd/deploy/trigger.go
- internal/cmd/deploy/trigger_test.go
- internal/resources/deploy/triggerstatus.go
This PR will add deploy trigger to trigger deploy and deprecate the `miactl deploy`. Furthermore, it's added a deploy add status command to update status based on a triggerId
> Add deploy trigger and deploy add status commands

- CHANGELOG.md
- internal/cmd/marketplace.go
- internal/cmd/marketplace/delete.go
- internal/cmd/marketplace/get.go
- internal/cmd/marketplace/list_versions.go
Removes from alpha build:
- `marketplace list-versions`
- `marketplace get` (only description updates)
- `marketplace delete` (only description updates)
From now on, these information (and the retrieval/deletion of marketplace items via itemId and tenantId) are available by default.
> feat: marketplace features removed from alpha build

- docs/30_commands.md
There were a few typos in the doc
> fix: typo in commands doc

- CHANGELOG.md
- internal/cmd/deploy/trigger.go
- internal/cmd/deploy/trigger_test.go
Right now the miactl deploy command return ok even when the pipeline ends with failure.
Using this command in a pipeline would mean to have a job that failed its operation but in the UI is succeeded.
With this PR, when the deploy fails the command returns an error "pipeline failed".
> Manage deploy pipeline error

- internal/cmd/marketplace/apply/apply_test.go
- internal/cmd/marketplace/apply/table.go
- internal/resources/marketplace/marketplace.go
Marketplace API, in particular the POST apply items, now has a new field that describes better the error regarding the item. I edited how the table is built so that now it shows the `errors` field, if exists.
> Read from errors field in apply items response body to display errors

- CHANGELOG.md
- internal/resources/responses.go
- internal/util/version_check.go
- internal/util/version_check_test.go
This PR will add a new utility function that can be used to query the remote server on which version has installed. This check can be used for selecting which APIs are available to the cli and maintain compatibility with older Console versions easier and cleaner.
> Add version check util function

- CHANGELOG.md
- internal/client/request.go
- internal/clioptions/clioptions.go
- internal/cmd/project.go
- internal/cmd/project/describe.go
- internal/cmd/project/describe_test.go
- internal/cmd/project/import.go
- tools/make/lint.mk
Adds a new command to describe the project configuration
> Adds `project describe` command
